name: Build Android APK

on:
  workflow_dispatch:

env:
  PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: "0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            automake \
            libltdl-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer cython

      - name: Prepare Android environment
        run: |
          buildozer android p4a -- --help

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AI-Video-Editor
          path: bin/*.apk
